### ISSUE TITLE
Inquiries about Light Matrix Coefficient.

### ISSUE THREAD

**Issue by nin0208** [visiont3lab/photometric_stereo#1]
Hello,

May I know how to enter the light matrix coefficient?

Can I input the angle between the light and the subject as the light matrix coefficient?

**Comment by thejauffre** [comment]
Hi!
To define the light matrix from the angles you can use [setlmfromts(tilt, slant)](https://github.com/visiont3lab/photometric_stereo/blob/c84d849d05f6e882d01dc0d0cdfa76774c526e5b/photostereo_py/script/photostereo.py#L132): tilts and slants are the angles between the scene center and the light sources (you can find some sample values in the [example.py](https://github.com/visiont3lab/photometric_stereo/blob/c84d849d05f6e882d01dc0d0cdfa76774c526e5b/photostereo_py/script/example.py#L33) script, and the explaination of tilt/slant in the Readme).
In that function you can see how the light matrix is constructed.
