### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by donyam** [visiont3lab/photometric_stereo#2]
line 53, in <module>
    normal_map = myps.runphotometry(image_array, np.asarray(mask, dtype=np.uint8))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by thejauffre** [comment]
Hi,
I'm missing some context here.
However, it seems you are trying to run the example without having correctly defined the *mask* image; maybe you are initializing it as *None*. Of course, numpy will raise that exception.
If you do not want to use the mask, you can run the algorithm using:
`
normal_map = myps.runphotometry(image_array)
`
